######################################################################
# Automatically generated by qmake (1.07a) N 7. sty 16:05:20 2007
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += mainform.h mainform.ui.h
SOURCES += main.cpp mainform.cpp
