######################################################################
# Automatically generated by qmake (1.07a) N 7. sty 15:56:03 2007
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += mainform.ui.h
INTERFACES += mainform.ui
SOURCES += main.cpp
