static const char* const image1_data[] = {
"311 31 330 2",
"#3 c #0c0c0c",
"#y c #0f0f0f",
"#5 c #121212",
"df c #141414",
"bD c #151515",
"bj c #181818",
".H c #1a1a1a",
"aR c #1b1b1b",
".o c #1d1d1d",
"#o c #1e1e1e",
"ce c #202020",
"a# c #212121",
"cf c #232323",
"cA c #262626",
"#Y c #272727",
"cp c #292929",
"bi c #2a2a2a",
"#D c #2c2c2c",
"a6 c #2d2d2d",
".K c #2f2f2f",
"ak c #303030",
".0 c #323232",
"aC c #333333",
"c9 c #353535",
"aj c #363636",
"cP c #3a3a3a",
".T c #3b3b3b",
"#V c #3c3b3c",
"cj c #3e3e3e",
"aq c #3f3f3f",
".E c #404040",
"b0 c #414141",
"bn c #424242",
".t c #434343",
"#n c #444444",
"cR c #464646",
"#B c #474747",
"a9 c #484848",
".u c #494949",
"#E c #4a4a4a",
"dc c #4c4c4c",
"aY c #4e4e4e",
"cu c #4f4f4f",
"#w c #505050",
"ao c #505150",
"c5 c #525252",
"#W c #535353",
".7 c #555555",
".j c #585858",
"#U c #595959",
"aD c #59595a",
"aX c #5a5a5a",
"cV c #5b5a5b",
"ct c #5b5b5b",
"#s c #5c5c5c",
"ax c #5d5c5c",
"bk c #5d5d5d",
"c7 c #5d5e5e",
"cT c #5e5d5e",
"ck c #5e5e5e",
"bM c #605f5f",
"ba c #606060",
"cK c #616161",
"c. c #626262",
".h c #636363",
".W c #646464",
"#Q c #656565",
"c1 c #666667",
"b6 c #686868",
"c3 c #696969",
".3 c #6a696a",
"co c #6a6a6a",
".m c #6c6c6c",
"#m c #6d6d6d",
"bw c #6f6f6f",
"#r c #707070",
"aP c #727272",
"#A c #737373",
"dh c #757575",
".5 c #757676",
"#u c #767676",
"bX c #777777",
"am c #777778",
"av c #777877",
"cY c #787878",
"b7 c #7a7a7a",
"bH c #7a7b7a",
"bU c #7b7a7b",
".D c #7b7b7b",
"c8 c #7d7d7d",
"#H c #7f7f7f",
"#1 c #7f807f",
".r c #808080",
"cN c #808180",
"#c c #818181",
"#2 c #828282",
"bN c #838383",
"a8 c #848383",
"bm c #848484",
"#I c #858584",
"bp c #868686",
"a7 c #878686",
"aT c #878687",
"bs c #878786",
".6 c #878787",
"cc c #888988",
".g c #898989",
"cl c #8b8b8a",
"#9 c #8b8b8c",
"b8 c #8b8c8b",
".4 c #8d8d8d",
"bZ c #8e8e8e",
"an c #8f8f8f",
"bB c #8f8f90",
"cH c #909090",
"#0 c #919191",
"cb c #919192",
"bI c #929292",
"#z c #949494",
"bv c #959595",
"aU c #969595",
"cm c #969797",
"#4 c #979797",
".i c #989898",
"aS c #989899",
"cC c #999899",
"#l c #9a9a99",
"#7 c #9a9a9a",
"al c #9b9b9b",
"bx c #9b9b9c",
"cJ c #9c9c9b",
"be c #9c9c9c",
"#6 c #9d9d9d",
"bL c #9e9e9e",
"a0 c #9e9f9e",
"a1 c #9f9e9e",
"bC c #9f9e9f",
"bf c #9f9f9f",
"de c #a0a0a0",
"aO c #a1a2a1",
"#v c #a2a2a2",
"b5 c #a3a3a3",
"aE c #a4a4a4",
"b# c #a5a4a4",
"#C c #a5a5a5",
"cX c #a6a7a6",
"aA c #a7a7a7",
"bq c #a7a8a7",
".8 c #a7a8a8",
"bd c #a8a8a8",
"ca c #a9aaaa",
"cd c #aaa9a9",
"ai c #aaaaaa",
"cF c #aaaaab",
"db c #acacac",
"aH c #adadad",
".9 c #adadae",
"aF c #b0b0b0",
"#x c #b1b0b1",
".v c #b2b2b2",
".V c #b3b3b3",
"bg c #b4b4b4",
"b3 c #b5b5b5",
"c4 c #b6b6b5",
"cn c #b7b7b7",
"dd c #b8b8b8",
"cI c #b9b9b9",
"cg c #b9baba",
"cq c #bababa",
"cZ c #bbbbbb",
"cy c #bcbbbc",
"a3 c #bcbcbc",
"#G c #bdbdbd",
"d# c #bebebe",
"cs c #bfbebf",
"a4 c #c0bfbf",
"ci c #c0c0c0",
"#Z c #c1c1c1",
".X c #c2c2c2",
"aZ c #c2c2c3",
"#F c #c3c3c3",
"ap c #c4c4c4",
"bG c #c5c4c4",
"cz c #c5c5c5",
"aW c #c6c5c5",
"bo c #c6c6c6",
".L c #c6c7c6",
"ay c #c7c7c7",
".1 c #c8c8c7",
"bt c #c8c8c9",
"#k c #c9c8c9",
".s c #c9c9c9",
"bV c #cacaca",
".2 c #cacacb",
"cB c #cacbcb",
"#t c #cccbcc",
"bl c #cccccc",
"c0 c #cccdcd",
"#R c #cdcdcd",
"dg c #cfcfce",
".k c #cfcfcf",
".I c #d0d0cf",
"bY c #d0d0d0",
".Y c #d1d1d1",
"#8 c #d2d2d2",
".F c #d3d3d2",
"aB c #d3d3d3",
"cD c #d3d3d4",
"cv c #d3d4d4",
"## c #d4d3d3",
"bE c #d4d4d5",
"ch c #d5d5d5",
"cU c #d6d6d5",
".U c #d7d6d6",
"az c #d7d7d6",
".q c #d8d8d8",
"#X c #d8d8d9",
"cE c #d9d9d9",
"bQ c #dad9d9",
"cx c #dadada",
"bF c #dadbdb",
"by c #dbdadb",
"bu c #dbdbda",
"#S c #dbdbdb",
"c6 c #dbdcdb",
"ar c #dcdcdc",
"bW c #dcdcdd",
"bJ c #dddddc",
"bA c #dddede",
"da c #dedede",
"b4 c #dfdede",
"cS c #dfdfde",
"bS c #dfdfdf",
"cw c #e0dfe0",
"bP c #e0e0df",
"#q c #e0e0e0",
"bz c #e1e0e0",
".e c #e1e1e1",
"cW c #e2e2e1",
"#b c #e2e2e2",
"aV c #e3e3e3",
".G c #e4e4e4",
"#a c #e5e5e4",
"cr c #e5e5e5",
"#p c #e6e6e6",
"cQ c #e7e6e6",
"cM c #e7e6e7",
"a. c #e7e7e7",
".n c #e9e9e9",
".J c #eaeaea",
"cG c #eaebea",
"as c #ebeceb",
"aw c #ececeb",
".p c #ececec",
"b2 c #ededed",
"b1 c #edeeed",
"bK c #eeeeee",
".l c #efefef",
"br c #efeff0",
"aQ c #eff0f0",
"cO c #f0efef",
"bh c #f0f0f0",
"#T c #f0f1f0",
"c# c #f1f0f0",
"ah c #f1f1f1",
"d. c #f2f2f2",
"a5 c #f3f2f2",
"bc c #f3f3f3",
"cL c #f4f3f4",
"bO c #f4f4f4",
"bT c #f5f4f4",
".f c #f5f5f4",
"au c #f5f5f5",
"c2 c #f6f6f5",
"bb c #f6f6f6",
"#. c #f6f6f7",
"b9 c #f6f7f7",
".Z c #f7f7f6",
"aG c #f7f7f7",
"bR c #f7f7f8",
".d c #f7f8f7",
".b c #f7f8f8",
".c c #f8f7f8",
".a c #f8f8f7",
".# c #f8f8f8",
".B c #f8f8f9",
".C c #f8f9f8",
".z c #f8f9f9",
".y c #f9f8f8",
".A c #f9f8f9",
".w c #f9f9f8",
".x c #f9f9f9",
".S c #f9f9fa",
".O c #f9faf9",
".M c #f9fafa",
".R c #faf9f9",
".P c #faf9fa",
".Q c #fafaf9",
".N c #fafafa",
"#i c #fafafb",
"#f c #fafbfa",
"#h c #fafbfb",
"#j c #fbfafa",
"#e c #fbfafb",
"#g c #fbfbfa",
"#d c #fbfbfb",
"a2 c #fbfbfc",
"b. c #fbfcfb",
"#K c #fcfcfc",
"#J c #fcfcfd",
"#N c #fcfdfc",
"#P c #fcfdfd",
"#M c #fdfcfc",
"#O c #fdfcfd",
"#L c #fdfdfc",
"ad c #fdfdfd",
"ab c #fdfdfe",
"aa c #fdfefd",
"ae c #fdfefe",
"af c #fefdfd",
"ac c #fefdfe",
"ag c #fefefd",
"at c #fefefe",
"aK c #fefeff",
"aJ c #fefffe",
"aL c #feffff",
"aM c #fffefe",
"aI c #fffeff",
"aN c #fffffe",
"Qt c #ffffff",
"Qt.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.a.#.#.#.#.#.#.#.a.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.a.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#"
".#.#.#.#.#.#.b.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#Qt",
"Qt.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.a.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.b.#.#.#.#.#.#.#.#.#.#.#.c.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#"
".#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.b.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.cQt",
"Qt.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.c.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.a.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.a.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.a.#.#.#.d.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.c.#"
".#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#Qt",
".e.b.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.c.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.c.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.b.#.#.#.#.#.#"
".#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.e",
".e.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.b.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.b.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.b.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.a.#"
".#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.c.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.a.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.e",
".e.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.f.g.h.i.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#"
".#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.e",
".e.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.c.#.#.#.#.#.#.#.#.#.#.#.#.b.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.c.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.g.j.k.h.g.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#"
".#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.a.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.e",
".e.a.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.c.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.b.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.c.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.l.m.k.n.#.#.c.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.l.o.p.#.q.r.s.t.u.v.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#"
".#.a.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.e",
".e.#.w.w.x.x.w.y.z.z.x.x.z.z.y.x.x.x.w.x.x.w.x.A.x.w.x.z.B.w.x.w.x.x.z.z.C.z.x.x.z.x.C.#.x.A.B.C.w.w.x.A.w.C.A.y.y.#.C.y.z.A.A.#.x.x.x.z.x.B.A.A.w.C.z.A.x.w.x.z.z.z.x.x.A.x.A.#.A.A.A.x.B.x.x.A.#.y.w.A.x.x.z.z.x.#.y.w.z.x.z.z.B.w.C.w.w.A.z.x.x.z.x.z.w.y.y.z.x.x.#.x.x.A.#.A.w.z.x.w.A.A.x.y.A.y.x.B.y.C.z.x.y.A.x.w.x.B.A.y.x.A.z.x.B.w.A.x.x.x.B.y.w.#.x.x.x.x.x.x.A.x.w.i.o.D.E.F.x.A.x.A.#.x.w.x.w.w.A.x.y.w.x.C.A.x.x.x.A.x.x.x.z.w.x.y.C.F.E.y.A.x.G.H.I.J.K.L.w.z.A.w.w.w.w.x.x.C.x.y.A.x.A.x.w.x.B.A.A.x.z.C.y.x.z"
".A.A.z.x.z.x.w.#.x.z.w.y.z.x.B.y.y.C.x.w.C.B.x.w.x.A.w.A.z.w.w.w.z.x.x.x.B.w.A.x.B.B.x.C.C.x.z.x.x.x.A.z.C.w.x.e",
".e.M.N.M.O.P.Q.Q.P.Q.N.M.O.O.O.N.N.x.N.N.R.x.R.Q.N.N.M.N.R.R.M.M.N.N.M.R.O.Q.O.N.N.R.P.P.S.Q.Q.P.S.Q.Q.N.R.O.S.R.N.Q.N.O.M.Q.Q.N.P.O.N.R.R.P.R.S.R.N.N.O.N.M.Q.x.Q.N.M.N.N.N.P.S.O.N.P.N.N.N.Q.Q.N.O.Q.N.N.P.N.P.N.P.M.M.N.Q.M.M.N.O.M.N.O.M.P.Q.P.P.Q.N.M.N.S.S.N.M.P.S.N.Q.P.Q.M.N.N.P.R.Q.R.P.M.S.N.x.Q.O.P.P.S.S.M.M.O.O.x.N.S.S.N.Q.P.P.N.O.M.N.P.N.R.N.R.P.N.P.N.N.N.N.R.T.U.M.V.W.N.X.Y.P.N.P.Q.Q.S.P.M.Q.M.Q.M.N.N.x.M.M.N.N.N.Q.N.N.P.S.P.Z.0.1.2.3.4.5.N.P.6.6.N.7.8.9#..S.x.N###a.N.Q.S.N.N.P.N.S.P.O.N.M.N.Q.x.M.N"
".N.N.Q.P.N.M.N.S.O.O.N.Q#b#c.N.N.N.x.N.P.S.M.N.Q.N.Q.M.P.N.P.M.N.R.S.R.N.M.O.N.x.R.P.P.Q.Q.N.O.Q.M.P.M.P.Q.R.R.e",
".e#d#e#d#d#f#d#d#e#d#g#h#d#h#d#d#e#d#d#g#d#d#d#d#d#d#d#e#e#d#g#d#d#d#d#d#g#d#d#d#d#d#d#d#i#d#h#d#d#e#d#d#d#d#d#d#d#d#d#f#d#d#f#g#d#h#d#h#h#d#d#e#i#d#h#d#i#d#d#d#e#d#g#g#g#d#d#g#f#g#d#d#d#d#g#d#d#d#d#d#d#d#d#d#h#d#d#d#d#d#d#d#d#g#e#h#d#d#d#d#e#d.N#d#h#h#d#h#i#d#d#d#g#j#d#d#g#d#g#d#d#d#e#d#h#d#d#g#d#d#d#d#d#d#g#d#f#d#d#d#d#d#d#d#d#g#d#d#d#g#h#d#i#d#d#d#d#d#d#g#d#d#k.T#d#e#l#m#h#n.T#o#p#g#d#d#d#g#g#g#g#d#d#d#d#d#d#j#d#g#d#g#d#d#d#d#d#g#q#r#s#t#u#v#d.N#w#x#q#y#z#A#B#d#h#C#D#E#F#q#h#d#d#d#d#d#d#g#d#g#d#d#d#h#d"
"#d#d#d#h#h#d#d#d.p.W#w#G#H#I#j#d#d#g#d#h#d#e#d#i#g#d#e#h#d#d#h#e#e#d#d#e#g#d#e#g#d#d#d#h#d#i#d#d#d#d#d#e#d#d#g.e",
".e#J#K#K#K#L#K#L#M#K#N#K#J#K#M#K#K#L#K#K#K#K#K#K#K#K#K#L#J#K#K#M#L#K#J#K#K#K#K#M#K#K#K#N#K#J#K#K#K#J#K#K#M#K#M#N#M#K#K#K#K#K#K#K#K#K#K#K#M#J#M#J#K#N#K#K#N#K#K#K#K#K#K#K#K#K#K#K#K#K#M#M#J#K#K#K#K#K#J#K#J#K#J#N#K#N#M#K#K#J#K#K#K#K#J#J#K#K#J#K#K#K#K#J#K#K#K#K#K#M#K#K#K#N#K#K#K#K#K#K#K#K#K#K#O#K#K#K#J#K#K#K#K#N#K#L#K#K#K#K#P#K#M#K#M#K#J#K#M#K#P#K#K#K#K#N#K#K#J#K#K#M#Q.K#O#..0#R#S#o#T.e#U#V#W#X#K#K#K#K#K#K#K#K#J#K#M#N#K#K#K#K#N#K#K#K#J#K#K#P#J#L#R#Y#Z#0.0.x#1#2#M.x#3#J#4#5#6#K#7#8#J#K#K#K#K#K#K#K#M#M#K#L#K#N#M"
"#K#K#N#K#K#J#K#K#U#9a.#Wa#a.#K#K#K#K#K#K#M#K#K#K#N#M#K#K#K#K#K#K#K#K#K#K#N#J#K#K#K#K#K#K#K#K#K#K#K#N#N#K#K#K#J.e",
".eaaabacacaaaaadaaadadadaeadadabafagaaafafagagadaaafadadadadadadaeaaagabacafaaadafacadabadadabafafabaaaaaeadaaadadafadafabadadafadadadadaeadagaeacafaaaaabafadabadabaaadabaaagadafadadadabadacafafaaababaaadafaaaaagababaaadafadaeabafadaeafaeabacadadabafaeabafabagadabaaadadaaadadaeaaadagababaeacadaaadadabadaeadadafacadaaagacabafagafadadadafadadadaaaaafaeaaadabadaaah#oaiajakalaeamanaaamaoadapaqadarasadatabagauaaadadadagacadaeadaaadadagaeadatafadad##av.gaw.N#Y.nac.Vaxadayaj.gazaAadatatadadaaadaeaaacaeaaababafae"
"afafadaeaeabafaBaCaaab.iaDabahaEaF#iafadaGaHaaafadadadagadatadabaeadadadaeadabadaeadafababadacadaaabaaataeafat.e",
".eaIaJataKaKatataJataLatatataMaLaNataNaLataJaJaMatataMataJaJaMaIataLaMaNaJataMatQtaMaMatatataKaJaKataMaMaLaMataJaJatataKaLaIataJaKQtataMaIaMaLataMaKaMataJaKaKataMaKaKaIaMQtaMaLataLaMataJaLaMaNaLaKaMaJatQtataIaMaKataMaNaMaMataIataLaLaIaJataKatQtaLataMatataLaIaKaLaJaKataIaNataKaKaNataKaJaJaIataIatatQtaKataMaMataIataJaMatatatataJataKaMataKatatataMataKataMataKaMaJaOaPaMaJaKat.wa#aQaKaR.maqaSa#aKaTaUatatatQtaqaVataKaMaJaMataKataMaIaMataMatataMaIaIataMataJaWaXQtaKaYaZaM.ha0aK.ma1aMaMa2aKaNataMaKaMaJaIataKaJaMaM"
"ataLaJQtataNaMa3.mataLaXa4a5a6a7a8a9b.aJb#baaMaLaMaMatatatataNataKaKataLaJaMaKaKaKaMataKaLaMataMaJatataMatatat.e",
".eQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtbbQtQtQtQtbcbdQtQtaR#KbbbeaPQt.6bfQtbgbaa.bhQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.GbiQtbhbjbbbba#bb#KbkaqajblbhQtQtQtQtQtQtQtQtQtQt"
"QtQtQtQtQtQtQtbbaj.s#CbiQtbm#obebcbk.kQtbnboQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.e",
".eaMaKatataNaMataJaJaMataJaLaIatataKaMataKaNatataIatataJaJaKQtaNaJaMaMaJataKaKataLataJaKaLatQtataMaKaKaMaKataJataJatatataLaJataNaJaNaLataKatataMaMataMaJaKaLQtaNataLaLaNatataLatQtaLaKaMataMataNaMataJaNaJatataMaJaMaLaIataKataNaJataMataKaJaLaJaJaLaMaLataMaJaJaNataIataLaJaMaNaJaJaMaKaJatatataJaJaJaJaNatataIatatatataMaMaMataKaMaLataJaNaNataJataNaMaMatatataKaKatataJaLaMaKaIatataKaMaIaLbpbkbqaYbratbsaEbta6#pbaaiatataLaKaJaLaNataJaKatQtaKatataKaMatataLaMaMatataJat.BbuatbvbwaKbxaPaL.gbaatby#5.iaMbzaJaJataJaKaNatat"
"ataJaKaMQtatataMbAbwaYbBQtaYa4bCa9bDbEbFa6ataKaKatataLaMaLataNaJaKaKaKaMataKaMaIaKatQtaIaLataKataMatataLaNaLaK.e",
".eadadacacadafabafabadaaaaadadaaafadabatadadacadadababadaaadadaaadabadafaaabafadadacadadadadadaaaaacaaaeadaaadadadaeabaeaeadadadadafadabagaaababagadadababaaadacafadafadafabadafatafaeadacaaadabadabaaadaaadafadafadaaadadabadabafadafadadacadaaabaaafaaaaadaeaaadadaaafabatabacaeaaadabaaagadadadabadadafabafafabafaaadaeaaafadadadaaadadaaafabaaadabadafagabadagadadadaaabafadadaaaaadacaaafacbGbv#ZaaabbHbIakbJbKa#aGaebLbMbNbOacabaaadagadafafafaaadaaafafadababadataaadafaaad##bPabaCbQaeaCaradbRbDahbSbiabadabadafadacad"
"adabadabaeaaatadaaadaGbTadbUbvafbQbVadaPbvaea3biaj#sbTadadbLbWabaeaaaaadafabadacadadagabadadabadabadagagacadac.e",
".e#K#O#K#N#K#J#K#P#K#K#K#K#K#N#M#M#M#J#M#K#K#K#K#J#K#K#K#K#K#K#K#J#K#M#K#K#K#K#N#K#K#K#L#J#K#K#J#K#O#J#K#K#K#K#K#K#K#K#J#K#K#K#K#K#K#K#N#K#K#K#M#K#K#K#J#K#K#K#K#K#K#K#L#K#N#J#N#P#P#K#J#K#K#K#K#K#K#K#K#K#J#K#K#K#K#J#K#N#K#K#K#P#K#N#K#K#L#M#K#N#N#K#M#K#K#K#J#M#K#N#K#K#K#J#K#K#J#K#M#K#N#K#K#J#K#N#J#K#K#K#K#K#K#K#J#L#K#M#N#J#N#K#M#K#K#J#K#K#K#J#K#M#K#K#M#K#K#K#K#K#K#K#K#O#N#K#N#K#K#K#J#J#K#N#K#KbX#obY#KbZbX#K#zb0b1#6#s#Kb2#K#K#K#L#K#K#K#K#K#K#K#M#J#K#J#K#N#K#K#N#K#N#N#K.xb3#M#Jb0b4#Kb5b6#Kb7b8#Kbb#Db9#K#K#K#J"
"#J#K#K#M#M#K#K#K#K#K#K#J#Kbcc..Ta#aybba#c#bhaRca#Kcbcc#Kcd#Y.O#K#K#M#L#K#K#N#M#K#P#K#J#K#K#K#N#K#K#K#K#K#O#K#M.e",
".e#e#d#d#d#g#d#d#d#d#g#d#d#d#h#d#g#g#d#d#d#d#d#d#e#d#j#g#d#d#d#e#d#d#d#e#d#d#g#d#d#d#d#d#d#h#d#d#d#d#d#e#d#d#g#g#g#d#d#d#d#g#d#d#d#d#d#d#d#d#e#d#d#d#d#d#d#d#j#g#g#d#d#d#d#g#d#d#d#d#h#d#g#d#e#d#d#d#d#d#d#g#d#d#d#d#d#h#d#d#d#d#h#g#d#h#d#d#d#d#d#d#d#h#d#d#d#d#h#g#d#d#d#e#d#d#g#e#h#d#d#g#d#d#d#d#d#e#d#d#e#g#d#d#d#d#d#d#d#d#g#d#h#f#d#h#h#j#h#h#d#d#d#d#d#e#d#g#d#d#i#d#d.N#d#d#d#g#e#d#e#g#g#d#d#d#e#S.k#d#d.K#S#dce.T#A.qcf#d.Wcg#e#d#h#d#d#d#d#e#e#d#d#d#d#d#d#d#e#d#d#d#d#i#d#h#d#dchcicjck#3#tbRce.n#d#Cck#dcl#ucm#d"
"#d#d#d#d#d#d#d#d#d#d#g#d#d#d#d#h#d#g#C.W#dcn#nck#Bcoco#d#scpcq#d#d#d#h#e#d#d#d#d#d#d#d#d#g#g#g#f#d#d#e#d#d#d#g.e",
".e.N.N.P.N.N.M.O.x.S.M.O.M.N.N.N.N.M.S.M.N.N.Q.N.Q.M.Q.P.P.M.M.S.S.N.P.P.M.P.P.Q.N.Q.O.N.M.P.N.x.R.N.S.Q.R.N.N.O.N.P.M.N.O.Q.N.Q.Q.S.x.N.R.N.P.O.Q.R.x.P.P.P.P.R.N.R.x.N.M.O.Q.N.S.P.N.Q.N.Q.N.Q.Q.M.Q.N.M.N.N.Q.x.Q.P.R.N.M.M.N.Q.N.Q.N.M.R.Q.P.N.P.N.P.N.N.R.S.P.M.N.M.M.N.M.O.R.Q.N.M.M.R.Q.M.P.N.Q.N.M.N.S.P.R.R.x.R.M.Q.N.M.N.R.M.N.O.M.R.O.P.N.S.N.M.R.P.N.M.N.N.Q.N.P.M.x.S.P.M.M.N.R.M.N.N.R.M.Q.x.P.N.Ncr#r.S.Z.o.Qcsctcj.xcucvcwcfcx.R.O.O.O.N.M.N.P.N.P.Q.S.Q.N.Q.Q.M.O.P.M.P.N.Nct.X.Qcy.T.P.X#n.O.N.Tcz.NcA#u#mcB"
"cC.X.x.Q.N.P.N.S.x.N.P.Q.R.R.N.N.P.McDcE.McFco.QcGcHcI.NcA#b.OcJcK.6cL.S.N.S.N.N.S.N.R.x.M.M.Q.R.x.P.O.R.M.P.Q.e",
".e.w.w.w.w.z.w.x.A.A.x.w.x.C.B.w.x.x.x.x.z.B.z.B.B.y.z.A.A.#.z.w.x.A.C.w.#.z.A.y.x.w.#.#.x.A.#.x.B.#.A.A.A.w.w.C.z.A.x.x.B.x.x.w.x.A.A.x.y.x.B.x.y.z.z.x.x.A.w.z.x.C.w.x.x.A.w.x.C.x.z.A.z.y.y.z.z.A.y.x.A.x.A.w.B.x.w.B.B.A.C.x.z.A.x.x.x.z.y.x.x.z.z.w.A.x.w.B.w.A.A.z.x.x.x.z.x.z.B.x.x.w.w.x.C.x.y.x.y.x.w.w.y.C.x.#.w.z.C.w.B.A.C.B.z.z.x.w.x.x.w.w.x.x.A.z.x.x.A.B.A.x.z.x.z.x.x.x.A.x.w.z.C.x.x.#.x.w.z.#.z.C.C.A.7bmcMcNcO.xcPcQcRcecQcScTbb.z.A.x.y.x.B.x.x.z.C.z.A.z.x.x.z.A.z.x.xcUcjcVcfay.zcWcfcXcY.0.xcZ.t.xc0#D"
"cHc1.D.A.z.x.x.x.A.x.w.x.w.y.x.x.C.x.A.A.wc2.u.Dc3cY.zc4c5.wbI.uc6alc7.A.w.A.x.z.C.C.A.x.x.x.z.C.A.z.x.B.w.y.x.e",
".e.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.c.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.a.#.b.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.pc8cub5.#.#c9aPbL.Kd.cPd#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.ed..#.#.#dabvcYbv.#.jdb.#dc.K"
"db.##Dd..#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#ddde.#.#.j.v.#cAcPcYdacp.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.e",
".e.#.#.#.#.#.#.#.a.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.a.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.b.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.H.hauc9baal.#.#.#.#.b.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.b.#.#.#.b.#.#.#.l#Dau.#df.e"
".rc9df.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#aX.mau.o.#dd.7c9.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.e",
".e.#.#.#.#.#.#.#.#.#.#.#.c.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.a.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.c.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#bL.l.q#ybw.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.a.#.#.#.#.#.#.#.#.#.#.#.#.#.t#F"
".#dg#F.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.a.#.#.#.#.#.#.#.#ch.#cub5.nbp.l.#.#.#.c.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.e",
".e.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.GbNau.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.q.7"
".K.K.e.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.pdhcPbL.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.e",
".e.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.b.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.b.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#"
".#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.a.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.b.#.#.#.#.#.#.#.#.c.#.#.#.e",
".e.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.a"
".#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.e",
".e.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.b.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.b.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#"
".#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.e",
".e.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.b.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.a.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.b.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.b.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#"
".#.#.#.#.#.#.#.#.#.#.#.b.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.e",
".e.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.b.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.c.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#"
".#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.a.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.e",
".e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e"
".e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e"};

